[project]
name = "dispersion-trading-hec-trading-club"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kevin Yang", email = "kevinyang4827@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.1.4",
    "pyarrow>=25.0.1",
    "scipy>=1.17.1",
    "sqlalchemy<2",
    "wrds>=3.1.6",
]

[project.scripts]
dispersion-trading-hec-trading-club = "dispersion_trading_hec_trading_club:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
